### ISSUE TITLE
Standalone v0.2 bug report

### ISSUE THREAD

**Issue by 60-hz** [timothyschoen/PlugData#10]
Very impressive work! Here is a few bug reports about  v0.2 of plugdata (standalone):
- Print object don't work
- Toggle should be at least square if not crossed to differanciate with bang
- hradio and vradio size return to default after switch action / edition mode
- Help only in edition mode, cannot switch into run mode
- vslider horizontal size grow when switching edition/action mode
- Save icon say "open" instead of "save"
- Out -> out connections are possible and should be disabled (now they seems to do same as out -> in)
- Object can still be edited in runmode

Few remarks:
- Click on cords to select it should be possible (not only drag a square around it)
- Shortcuts to create new boxes
- New objects should appear under current mouse position
- Objects box should resize while adding letter inside
- vsl/hsl slider grey bar should be visible to see where we are in the range
- title name Label takes too much space, maybe the name could appear on mouse over only
- all gui could also be triggered in editmode (pd use ctrl + clic in edit to temporary switch to runmode)

Looking forward to see how it will grow ;)

**Comment by timothyschoen** [comment]
Very useful, this will be my new todo list.

**Comment by timothyschoen** [comment]
Shortcuts to create new boxes actually already exist. For the most part, they're the same as Max (b = bang, t = toggle, m = msg, n = empty, s = vsl, i = numbox, f = floatatom). Maybe they should be changeable in settings eventually. When using these shortcuts, the new object will appear at mouse position.

**Comment by timothyschoen** [comment]
All these issues should be fixed!

**Comment by 60-hz** [comment]
Great! like v0.1, v0.2.1 is not compatible with OSX 10.15.4 ;)

**Comment by timothyschoen** [comment]
oh no... I did notice an issue (app was not openable) a few minutes ago and quickly replaced the macOS build... I hope you downloaded it before the update ;)

**Comment by 60-hz** [comment]
I tried again, but unfortunately the app is still not compatible.

**Comment by timothyschoen** [comment]
Hmm that's unfortunate. I don't have any Macs running Catalina, so this is hard to debug for me. Is it alright if I send you another version to try tonight? (test it whenever you have time)

**Comment by timothyschoen** [comment]
I see that since commit 2c8eb55, the macOS executable generated in the automatic build action is no longer executable. I thought I had fixed it by building it manually, but apparently there's something wrong, I'll get this sorted out,

**Comment by timothyschoen** [comment]
I've updated the release with a new version that should work on Catalina, @60-hz does it work again now?

**Comment by 60-hz** [comment]
It works ;)
